server
{
listen 80;
    listen 443 ssl default_server;
    listen 443 quic default_server;
    http2 on;
   server_name yangyangyunhe.cloud www.yangyangyunhe.cloud;
    index index.html index.htm default.htm default.html;
    include /www/server/panel/vhost/nginx/extension/娉辨潮浜戝悎AI鍒剁墖鍘?*.conf;
    #    root /www/wwwroot/beehive-platform;
    #CERT-APPLY-CHECK--START
    # 鐢ㄤ簬SSL璇佷功鐢宠鏃剁殑鏂囦欢楠岃瘉鐩稿叧閰嶇疆 -- 璇峰嬁鍒犻櫎
    include /www/server/panel/vhost/nginx/well-known/娉辨潮浜戝悎AI鍒剁墖鍘?conf;
    #CERT-APPLY-CHECK--END


    #SSL-START SSL鐩稿叧閰嶇疆
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    set $isRedcert 1;
    if ($server_port != 443) {
        set $isRedcert 2;
    }
    if ( $uri ~ /\.well-known/ ) {
        set $isRedcert 1;
    }
    if ($isRedcert != 1) {
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/娉辨潮浜戝悎AI鍒剁墖鍘?fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/娉辨潮浜戝悎AI鍒剁墖鍘?privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_tickets on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    add_header Alt-Svc 'quic=":443"; h3=":443"; h3-29=":443"; h3-27=":443";h3-25=":443"; h3-T050=":443"; h3-Q050=":443";h3-Q049=":443";h3-Q048=":443"; h3-Q046=":443"; h3-Q043=":443"';
    error_page 497  https://$host$request_uri;

    
    #SSL-END

    #ERROR-PAGE-START  閿欒椤电浉鍏抽厤缃?    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END


    #REWRITE-START 浼潤鎬佺浉鍏抽厤缃?    include /www/server/panel/vhost/rewrite/node_娉辨潮浜戝悎AI鍒剁墖鍘?conf;
    #REWRITE-END

    # 绂佹璁块棶鐨勬晱鎰熸枃浠?    location ~* (\.user.ini|\.htaccess|\.htpasswd|\.env.*|\.project|\.bashrc|\.bash_profile|\.bash_logout|\.DS_Store|\.gitignore|\.gitattributes|LICENSE|README\.md|CLAUDE\.md|CHANGELOG\.md|CHANGELOG|CONTRIBUTING\.md|TODO\.md|FAQ\.md|composer\.json|composer\.lock|package(-lock)?\.json|yarn\.lock|pnpm-lock\.yaml|\.\w+~|\.swp|\.swo|\.bak(up)?|\.old|\.tmp|\.temp|\.log|\.sql(\.gz)?|docker-compose\.yml|docker\.env|Dockerfile|\.csproj|\.sln|Cargo\.toml|Cargo\.lock|go\.mod|go\.sum|phpunit\.xml|phpunit\.xml|pom\.xml|build\.gradl|pyproject\.toml|requirements\.txt|application(-\w+)?\.(ya?ml|properties))$
    {
        return 404;
    }

    # 绂佹璁块棶鐨勬晱鎰熺洰褰?    location ~* /(\.git|\.svn|\.bzr|\.vscode|\.claude|\.idea|\.ssh|\.github|\.npm|\.yarn|\.pnpm|\.cache|\.husky|\.turbo|\.next|\.nuxt|node_modules|runtime)/ {
        return 404;
    }

    #涓€閿敵璇稴SL璇佷功楠岃瘉鐩綍鐩稿叧璁剧疆
    location /.well-known/ {
        root  /www/wwwroot/beehive-platform;
    }

    #绂佹鍦ㄨ瘉涔﹂獙璇佺洰褰曟斁鍏ユ晱鎰熸枃浠?    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }


    # HTTP鍙嶅悜浠ｇ悊鐩稿叧閰嶇疆寮€濮?>>>
    location ~ /purge(/.*) {
        proxy_cache_purge cache_one $host$request_uri$is_args$args;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        add_header X-Cache $upstream_cache_status;
        proxy_set_header X-Host $host:$server_port;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 30s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # 绂佺敤HTML浠ｇ悊缂撳瓨
        proxy_no_cache 1;
        proxy_cache_bypass 1;
    }
    # HTTP鍙嶅悜浠ｇ悊鐩稿叧閰嶇疆缁撴潫 <<<

    access_log  /www/wwwlogs/娉辨潮浜戝悎AI鍒剁墖鍘?log;
    error_log  /www/wwwlogs/娉辨潮浜戝悎AI鍒剁墖鍘?error.log;
}
